### ISSUE TITLE
Error while starting cluster

### ISSUE THREAD

**Issue by jasiedu** [pgm/flock#2]
Got the following error while starting a cluster

> > > Running plugin deadmansSwitch
> > > **\* WARNING - Verifying that domain hoc-heartbeats is accessible with non-admin credentials
> > > tmpV5pOIh 100% |||||||||||||||||||||||||||||||||||||| Time: 00:00:00   2.32 M/s
> > > **\* WARNING - Adding cronjob for checking deadmans switch on <Node: hoc-master (i-30f64fc0)>
> > > Running plugin installWingmanService
> > > !!! ERROR - Error occured while running plugin 'installWingmanService':
> > > !!! ERROR - Unhandled exception occured
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 274, in main
> > >     sc.execute(args)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/start.py", line 282, in execute
> > >     save_config_on_master=self.opts.config_on_master)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1852, in start
> > >     save_config_on_master=save_config_on_master)
> > >   File "<string>", line 2, in _start
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/utils.py", line 112, in wrap_f
> > >     res = func(_arg, *_kargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1876, in _start
> > >     self.setup_cluster(save_config_on_master)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1885, in setup_cluster
> > >     self._setup_cluster(save_config_on_master)
> > >   File "<string>", line 2, in _setup_cluster
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/utils.py", line 112, in wrap_f
> > >     res = func(_arg, *_kargs)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1899, in _setup_cluster
> > >     self.run_plugins()
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1918, in run_plugins
> > >     nodes=nodes)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1946, in run_plugin
> > >     func(*args)
> > >   File "/home/ubuntu/.starcluster/plugins/sc_flock_plugins.py", line 142, in run
> > >     temp_wingman_script.write(wingman_script_template(flock_home=self.flock_home, run_dir=self.run_dir))
> > > TypeError: 'Template' object is not callable
> > > !!! ERROR - Oops! Looks like you've found a bug in StarCluster

!!! ERROR - Crash report written to: /home/ubuntu/.starcluster/logs/crash-report-2800.txt
!!! ERROR - Please remove any sensitive data from the crash report
!!! ERROR - and submit it to starcluster@mit.edu

**Comment by pgm** [comment]
Yes, that's clearly broken.  I checked in a fix, but have not tested it.  As I mentioned earlier, when I moved all the plugins around, I haven't had a chance to test them.  I must have introduced this problem then somehow.

I'll upgrade my environments to latest from git to confirm everything is still working.

**Comment by jasiedu** [comment]
New Error. See below. Missing wingman.conf. 

**\* WARNING - Adding cronjob for checking deadmans switch on <Node: hoc-master (i-42a92db2)>

> > > Running plugin installWingmanService
> > > !!! ERROR - Error occured while running plugin 'installWingmanService':
> > > !!! ERROR - [Errno 2] No such file or directory:
> > > !!! ERROR - '/home/vagrant/.starcluster/plugins/wingman.conf'

**Comment by jasiedu** [comment]
When i copied the wingman.conf file from stash and deposited it into the plugins directory on my cluster, it resolved the issue. So I am going to add the wingman.conf file here.

**Comment by pgm** [comment]
Yes, I missed copying the config file from the "starcluster-setup"
project.  That file is now in the repo too now.   (Under "starcluster"
along with the other plugin files.)

**Comment by pgm** [comment]
Oh!  Sounds like you did exactly the same thing.  Great, thanks.
